//---------------------------------------------------------------------------
//-- Shared compiler helpers: header, module, mainIO, getInitPorts,
//-- getInitPins, findBlock
//---------------------------------------------------------------------------
'use strict';

window._icecompiler = window._icecompiler || {};

window._icecompiler.helpers = function (ctx) {
  function header(comment, opt, linterRules) {
    var _header = '';
    var date = new Date();
    opt = opt || {};
    linterRules = linterRules || false;
    if (opt.header !== false) {
      _header +=
        comment + ' Code generated by Icestudio ' + ctx._package.version + '\n';
      if (linterRules) {
        _header += comment + '  #START Verilator Linter rules:' + '\n';
        _header += '/* verilator lint_off PINMISSING */' + '\n';
        _header += '/* verilator lint_off WIDTHTRUNC */' + '\n';
        _header += '/* verilator lint_off WIDTHEXPAND */' + '\n';
        _header += comment + '  #END Verilator Linter rules' + '\n';
      }
      if (opt.datetime !== false) {
        _header += comment + ' ' + date.toUTCString() + '\n';
      }
      _header += '\n';
    }
    return _header;
  }

  function module(data) {
    var code = '';
    if (data && data.name && data.ports) {
      // Header
      code += '\nmodule ' + data.name;

      //-- Parameters

      var params = [];
      let pname = '';
      for (var p in data.params) {
        if (data.params[p] instanceof Object) {
          pname =
            data.params[p].name.charAt(0) === '@'
              ? data.params[p].name.substr(1)
              : data.params[p].name;
          params.push(
            ' parameter ' +
              pname +
              ' = ' +
              (data.params[p].value ? data.params[p].value : '0')
          );
        }
      }

      if (params.length > 0) {
        code += ' #(\n';
        code += params.join(',\n');
        code += '\n)';
      }

      //-- Ports

      var ports = [];
      let i, o, _in, _out, _inout;

      // Strip legacy @ (signed) and # (registered) prefixes from old projects
      var stripLegacyPrefixes = function (name) {
        return name.replace(/^[@#]+/, '');
      };

      for (i in data.ports.in) {
        _in = data.ports.in[i];
        pname = stripLegacyPrefixes(_in.name);
        ports.push(' input ' + (_in.range ? _in.range + ' ' : '') + pname);
      }

      for (o in data.ports.out) {
        _out = data.ports.out[o];
        pname = stripLegacyPrefixes(_out.name);
        ports.push(' output ' + (_out.range ? _out.range + ' ' : '') + pname);
      }

      for (i in data.ports.inout) {
        _inout = data.ports.inout[i];
        pname = stripLegacyPrefixes(_inout.name);
        ports.push(
          ' inout ' + (_inout.range ? _inout.range + ' ' : '') + pname
        );
      }

      for (i in data.ports.inoutLeft) {
        _in = data.ports.inoutLeft[i];
        pname = stripLegacyPrefixes(_in.name);
        ports.push(' inout ' + (_in.range ? _in.range + ' ' : '') + pname);
      }

      for (o in data.ports.inoutRight) {
        _out = data.ports.inoutRight[o];
        pname = stripLegacyPrefixes(_out.name);
        ports.push(' inout ' + (_out.range ? _out.range + ' ' : '') + pname);
      }

      if (ports.length > 0) {
        code += ' (\n';
        code += ports.join(',\n');
        code += '\n)';
      }

      if (params.length === 0 && ports.length === 0) {
        code += '\n';
      }

      code += ';\n';

      // Content

      if (data.content) {
        var content = data.content.split('\n');

        content.forEach(function (element, index, array) {
          array[index] = ' ' + element;
        });

        code += content.join('\n');
      }

      // Footer

      code += '\nendmodule\n';
    }

    return code;
  }

  function getInitPorts(project) {
    // Find not connected input wire ports to initialize

    var i, j;
    var initPorts = [];
    var blockArray = project.design.graph.blocks;

    // Find all not connected input ports:
    // - Code blocks
    // - Generic blocks
    for (i in blockArray) {
      var block = blockArray[i];
      if (block) {
        if (
          block.type === ctx.blocks.BASIC_CODE ||
          !block.type.startsWith('basic.')
        ) {
          // Code block or Generic block
          for (j in block.data.ports.in) {
            var inPort = block.data.ports.in[j];
            if (inPort.default && inPort.default.apply) {
              initPorts.push({
                block: block.id,
                port: inPort.name,
                name: inPort.default.port,
                pin: inPort.default.pin,
              });
            }
          }
        }
      }
    }

    return initPorts;
  }

  function getInitPins(project) {
    // Find not used output pins to initialize

    var i;
    var initPins = [];
    var usedPins = [];
    var blockArray = project.design.graph.blocks;

    // Find all set output pins
    for (i in blockArray) {
      var block = blockArray[i];
      if (block.type === ctx.blocks.BASIC_OUTPUT) {
        for (var p in block.data.pins) {
          usedPins.push(block.data.virtual ? '' : block.data.pins[p].value);
        }
      }
    }

    // Filter pins defined in rules
    var allInitPins = ctx.common.selectedBoard.rules.output;
    for (i in allInitPins) {
      if (usedPins.indexOf(allInitPins[i].pin) === -1) {
        initPins.push(allInitPins[i]);
      }
    }

    return initPins;
  }

  function mainIO(project) {
    var input = [];
    var output = [];
    var inputUnnamed = 0;
    var outputUnnamed = 0;
    var graph = project.design.graph;
    let pname = '';
    for (var i in graph.blocks) {
      var block = graph.blocks[i];
      if (block.type === ctx.blocks.BASIC_INPUT) {
        if (block.data.name) {
          pname = block.data.name.replace('@', '');
          input.push({
            id: ctx.utils.digestId(block.id),
            name: pname.replace(/ /g, '_'),
            range: block.data.range,
          });
        } else {
          input.push({
            id: ctx.utils.digestId(block.id),
            name: inputUnnamed.toString(),
          });
          inputUnnamed += 1;
        }
      } else if (block.type === ctx.blocks.BASIC_OUTPUT) {
        if (block.data.name) {
          pname = block.data.name.replace('@', '');
          output.push({
            id: ctx.utils.digestId(block.id),
            name: pname.replace(/ /g, '_'),
            range: block.data.range,
          });
        } else {
          output.push({
            id: ctx.utils.digestId(block.id),
            name: outputUnnamed.toString(),
          });
          outputUnnamed += 1;
        }
      }
    }

    return {
      input: input,
      output: output,
    };
  }

  function findBlock(id, graph) {
    for (var b in graph.blocks) {
      if (graph.blocks[b].id === id) {
        return graph.blocks[b];
      }
    }
    return null;
  }

  return {
    header: header,
    module: module,
    getInitPorts: getInitPorts,
    getInitPins: getInitPins,
    mainIO: mainIO,
    findBlock: findBlock,
  };
};
