// Code generated by Icestudio 0.12
// Mon, 16 Feb 2026 13:25:00 GMT

`default_nettype none

//---- Top entity
module main (
 input v2bc900,
 input [7:0] v8d8391,
 output vfe1227,
 output v2c3842
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 assign w0 = v8d8391;
 assign vfe1227 = w2;
 assign v2c3842 = w4;
 assign w5 = v2bc900;
 assign w6 = v2bc900;
 assign w6 = w5;
 main_v1f17c3 v1f17c3 (
  .config_reg(w0),
  .en_led(w1),
  .en_but(w3)
 );
 v58ed2b vae6662 (
  .vf54559(w1),
  .ve8318d(w2),
  .va4102a(w5)
 );
 v58ed2b v4fb1e0 (
  .vf54559(w3),
  .ve8318d(w4),
  .va4102a(w6)
 );
endmodule

//---- Top entity
module v58ed2b #(
 parameter v71e305 = 0
) (
 input va4102a,
 input vf54559,
 output va58c5b,
 output ve8318d
);
 localparam p2 = v71e305;
 wire w0;
 wire w1;
 wire w3;
 assign w0 = va4102a;
 assign ve8318d = w1;
 assign w3 = vf54559;
 v58ed2b_vb8adf8 #(
  .INI(p2)
 ) vb8adf8 (
  .clk(w0),
  .q(w1),
  .d(w3)
 );
endmodule

//---------------------------------------------------
//-- sys-DFF-verilog
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- System - D Flip-flop. Capture data every system clock cycle. Verilog implementation
//---------------------------------------------------

module v58ed2b_vb8adf8 #(
 parameter INI = 0
) (
 input clk,
 input d,
 output q
);
 //-- Initial value
 reg qi = INI;
 
 //-- Capture the input data  
 //-- on the rising edge of  
 //-- the system clock
 always @(posedge clk)
   qi <= d;
   
 //-- Connect the register with the
 //-- output
 assign q = qi;
endmodule

module main_v1f17c3 (
 input [7:0] config_reg,
 output en_led,
 output en_but
);
 assign en_led = config_reg[0] &! config_reg[1];
 assign en_but = config_reg[1] &! config_reg[0];
endmodule
